### ISSUE TITLE
[Proposal] Optimization for Translation Files

### ISSUE THREAD

**Issue by Nacosia** [Ada18980/KinkiestDungeon#125]
Recently, while working on translations, I've identified some areas for improvement:

1. Standardizing the work of translators to avoid confusion in the positioning of translated entries and potential misuse or reuse issues.
2. Enhancing the experience of translators by eliminating the need to search for entries in a CSV file and paste them.

Before proceeding with the detailed design, I would like to seek your opinion, as I understand that such changes may impact existing users and may require additional support from project maintainers. Here are my preliminary thoughts on the reconstruction of this module:

In the following content, I will use `csv` to refer to the original text and `lang.txt` to denote the translated text in various languages. I will use the following csv as a benchmark example:

```csv
TYPE1_A, text1
TYPE1_B, text2

TYPE2_C, text3

TYPE3_D, text4
TYPE3_E, text5
```

##### lang.txt
```
text1
translate1
text2
translate2

text3
translate4
```

#### 2. Declare untranslated terms in advance, so that translators do not need to consult the CSV file.

I would like to disrupt the translation matching mechanism by adding a `# ` at the beginning, so that the application does not parse it. However, I have not read the source code and am not sure if this will cause confusion in the program's operation, so I remain uncertain about its feasibility.

```
...
# text4
# text5
```
> This way, translators do not need to consult the contents of the CSV file, they can simply remove the `# ` to complete the translation.

I plan to accomplish this task using Python.
> If possible, we might also be able to call an automatic translation API for translations

Next, I might use GitHub Actions to monitor commits to `Screens/MiniGame/KinkyDungeon/Text_KinkyDungeon.csv` and execute the Python script to sync with other `lang.txt` files.

What are your thoughts on this? Do you believe this reconstruction is feasible?

Thank you very much for your time and consideration. I look forward to your response! If it's feasible, I will start preparing. :)

**Comment by Mitki-code** [comment]
其实吧，你说的第一点，是可以随便换行的，因为逻辑是读到原文本后，替换为下一行的翻译文本（差不多这个意思）。第二点，随便用，只要不是原文本就行。
