### ISSUE TITLE
Can step inside another entitity if pathing into the same tile when first loading a save

### ISSUE THREAD

**Issue by glop102** [Ada18980/KinkiestDungeon#21]
Specific situation this is observed.
- Load the below save
- observe the entity `Ranger of the Wild` is stepping north
- click to move on to the same tile as it is pathing in to
- You are now on the same tile as the ranger. You you do the fast wait button on the bottom, it immediately is interrupted and brings up the dialog as if you clicked on them.

data from the variable "KinkyDungeonSave"

```
N4IgNgpgbhYgXADgDQgMYAsJoNYAcB7ASwDsAXBEAcwCcoRUaI8FQBxDAgZwvgFoALAE5UABRpEuBEhBoIBKEABkIAQzJY5/BagCyEMqrj8AzAAZUAJQJ4ICQYqXqIAD3smATKgDqRMMcEAVlQAUUgAWwhyLnsPYJAAYWkAKwBXJnsBAVQASX9UriJpe0CzAF9UNG4yGPhQJPDImjQ7eABGCxB9Q2MvEDCISOiENtQVdU0RipA8Kp5a4GmAEyYuWpAAeQAjQqWiVRIGagIwJYQTIUQ+wlIahHiiM/hAoQA2PsxiFtqAbQsTZDBADsyDaXhIqX8oKBAF1KpwiN8PAgfmQaKkIMgAGZGLiYtEY5AE/HozEQqHEuEgLapLFYhYgAAqiJwYEkGFYIEelGZuDZXA5qDIAE9bJQyCzIAARVThVRUCCWCCFHhHQgAd1k9jMADp4kt0uoiod4B5pk4uGgiFAigVOdz4MpVJbrbaYkLRa1qDQbBAZXKFUqVRRUBqtfxdfrDRLiqbpqJVKRGSdZAcWvaniAE0mUzQ03YPWLHXhEyR/fLFcrJCGZgRNVo+ga8zGTWarEQqAqaG0M5RLB2uz3C16qGAMeWFQAhWlYtV18O6xvR40INsgfud2TIupczMbrvI4eUTClicQad0uf1hCL1BNo2xtf72QmXuO580V9Hx2T0hLACC4QsKG85aLqAIgPeLartMIRQM61oQD2O4Ov08GFDAQ4gCKRZoQhxQgde8C6qMkHLrGbTTAAyhgEgyAMQx3ChmY0XREAMVEdzfiA0CcUccouEkqTkCMnSGFQvwgAQdJRHiRwCmxHHDFSqiGpQADEWJtK8AhtLOhHhm0ep3uRJomIEwioLxwzwD8oBogO4YgKoWJkLIZ4hDI4TCkcOFeqxpDsREnHuiAXC2P4lD/s0BwQFRDk4HYZRUmg6RMOQQkifAQLTJOBDCUsoigW+IB5QVRXXtxcH4YcJnNiu7QGWBOpmAIZjtR
```

Attempts at replicating this with other entities - without being a fresh load into the level
- Maidforce Recruit heading south/south-east/north-east/north - entity redirects to a different tile
- Latex Apprentice heading west/south/south-west/north-east/east/north-west - entity redirects to a different tile
- Ranger of the Wild heading west - entity redirects to a different tile

Reproduction attempts immediately after loading a save
- Ranger of the Wild heading north - Yep
- Latex Apprentice heading east - Yep

Totally understandable if you don't care to fix this since it seems to only happen on loading a save, but i can see someone perhaps finding a way to abuse this in tight quarters combat or something.

**Comment by Ada18980** [comment]
Hm, thanks for letting me know. It should be a simple matter of setting a
flag to refresh the enemy cache
