### ISSUE TITLE
New Artwork Graphic bugs

### ISSUE THREAD

**Issue by Nep-Timeline** [Ada18980/KinkiestDungeon#57]
* [x]   1. Foot malposition
![9957ae382da8d1cc36c332e55a3f1aa1](https://github.com/Ada18980/KinkiestDungeon/assets/53483352/5d91ee14-4961-466f-bacb-5797fb93c305)
* [x]   2. Rubber has some issues
![b47f866526b27f163e66c75e09d44150](https://github.com/Ada18980/KinkiestDungeon/assets/53483352/1f7d9a9d-4924-4b46-a145-d0ff6b78a3a0)
If the shoes are Leather Heels
![1546bb982e2a0b953ac0d53236e50c9a](https://github.com/Ada18980/KinkiestDungeon/assets/53483352/ba2e7065-f603-49b3-9dc7-b5b0f81fa98a)
* [x]   3. Glove Right
![54d08cfb7b90407dcb0369e3e854e34d](https://github.com/Ada18980/KinkiestDungeon/assets/53483352/a9e10cef-0a05-49bf-a34b-2bea41eae845)
* [x]   4. Bind ballet heels
![image](https://github.com/Ada18980/KinkiestDungeon/assets/53483352/e918d53a-5298-46b6-a251-f48d852fdeef)

**Comment by Ada18980** [comment]
Thanks for catching! Must have left the sock out of the displacement map by accident.

**Comment by Ada18980** [comment]
#1 should be resolved soon
Will take a look at the other two
