### ISSUE TITLE
Foot malposition issues still exist

### ISSUE THREAD

**Issue by Nep-Timeline** [Ada18980/KinkiestDungeon#63]
![image](https://github.com/Ada18980/KinkiestDungeon/assets/53483352/9b751ed9-78f6-49f3-a253-8a90dd4d9de5)

**Comment by Ada18980** [comment]
Good catch I will look today. Need to add foot wrapping to heels erase map

**Comment by Ada18980** [comment]
Hopefully fixed in 5.0.1!
