### ISSUE TITLE
Automatic path finding through vertical doors not working.

### ISSUE THREAD

**Issue by glop102** [Ada18980/KinkiestDungeon#9]
The new vertical doors look nice, but to walk through them, you have to click directly on them and then continue on.
This also leads to some very funky path finding where it will route a long way around to get to the next room.

**Comment by glop102** [comment]
I got caught after this change, and i am "being taken to another cell" but the pathing is also broken, likely for the same reason.

**Comment by Ada18980** [comment]
The new vertical door sprites have nothing to do with pathfinding, that
might be a separate issue

**Comment by Ada18980** [comment]
Nevermind I'm wrong! I dont think it will break the jail pathfinding though

**Comment by Ada18980** [comment]
Okay I believe both issues are fixed. Let me know if this is still happening for you!

**Comment by glop102** [comment]
Hurrah! Yep, that fixed it.
FYI: With GIthub, you can put something like "Fixes Whatever #9" and it should automatically make a note here in the issue
